package com.connectai.agent;

import java.util.Objects;
import java.util.UUID;

/**
 * User-safe evidence extracted from a successful dynamic tool execution.
 *
 * The citation id is generated by Connect AI and is not supplied by the model.
 */
public record GroundedEvidence(
        String citation,
        int stepNumber,
        UUID serverId,
        String toolName,
        String content
) {
    public GroundedEvidence {
        Objects.requireNonNull(citation, "citation");
        Objects.requireNonNull(serverId, "serverId");
        Objects.requireNonNull(toolName, "toolName");
        Objects.requireNonNull(content, "content");

        if (citation.isBlank()) {
            throw new IllegalArgumentException("citation must not be blank");
        }
        if (stepNumber <= 0) {
            throw new IllegalArgumentException("stepNumber must be greater than zero");
        }
        if (toolName.isBlank()) {
            throw new IllegalArgumentException("toolName must not be blank");
        }
        if (content.isBlank()) {
            throw new IllegalArgumentException("content must not be blank");
        }
    }
}
